### ISSUE TITLE
Allow setting the SAML Nameidentifier

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3.WsFederation#23]
http://zamd.net/2015/02/06/federating-azure-ad-with-thinktecture-identity-server-notes/

**Comment by VictorBlomberg** [comment]
Hi,

In case anyone else have the same issue: With this change, it appears you have to explicitly set `SamlNameIdentifierFormat = ClaimProperties.SamlNameIdentifierFormat` on the RelyingParty to keep the previous behavior if you have a ClaimMapping for NameIdentifier, otherwise the NameIdentifier claim will be filtered out.

(I do think this could have been documented clearer.)

**Comment by leastprivilege** [comment]
That would be a bug.

**Comment by VictorBlomberg** [comment]
Ah, that explains the lack of documentation! Good then, it was an easy one to work around.

Thanks!

**Comment by TheBeardedLlama** [comment]
I wish I'd seen this bug report earlier @VictorBlomberg 

I take it this is yet to be fixed?

**Comment by VictorBlomberg** [comment]
By looking at RelyingParty.cs, I would say not changed/fixed.

**Comment by TheBeardedLlama** [comment]
yeah that's what I thought as well

the history is a bit confusing

is it still considered a bug @leastprivilege?

**Comment by leastprivilege** [comment]
I can't remember - didn't @VictorBlomberg have a solution for it?

**Comment by VictorBlomberg** [comment]
Well, the solution/work around was explicitly set SamlNameIdentifierFormat = ClaimProperties.SamlNameIdentifierFormat on the RelyingParty entity.

**Comment by TheBeardedLlama** [comment]
so I suppose the question is if it should be set with the other defaults in the constructor

if not, then there should be some indication really that it should be, otherwise it won't work...
